name: xLightsabers
version: '${project.version}'
main: com.forcemc.lightsabers.Lightsabers
api-version: 1.19
authors: [ eenarmige_klasse ]
depend:
  - BKCommonLib
  - MMOItems
commands:
  lightsabers:
    description: Lightsaber command
    aliases: lightsabers